// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KI66KXsqqndTHQ9EKITzTC1PzvBU5sg',
    appId: '1:428595049201:web:051fc81ca61d2f6b21af50',
    messagingSenderId: '428595049201',
    projectId: 'my-ecommerce-app-159',
    authDomain: 'my-ecommerce-app-159.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrS4k10gMHsQktYcvK6C_rJ97UTkIoZQk',
    appId: '1:428595049201:android:c943eef1c753512621af50',
    messagingSenderId: '428595049201',
    projectId: 'my-ecommerce-app-159',
    storageBucket: 'my-ecommerce-app-159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUYwhMPPIWT2qBBUq9d63zVC3fztP2Fp0',
    appId: '1:428595049201:ios:cb767d6f0eddb31121af50',
    messagingSenderId: '428595049201',
    projectId: 'my-ecommerce-app-159',
    storageBucket: 'my-ecommerce-app-159.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUYwhMPPIWT2qBBUq9d63zVC3fztP2Fp0',
    appId: '1:428595049201:ios:cb767d6f0eddb31121af50',
    messagingSenderId: '428595049201',
    projectId: 'my-ecommerce-app-159',
    storageBucket: 'my-ecommerce-app-159.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9KI66KXsqqndTHQ9EKITzTC1PzvBU5sg',
    appId: '1:428595049201:web:785404a995dc694521af50',
    messagingSenderId: '428595049201',
    projectId: 'my-ecommerce-app-159',
    authDomain: 'my-ecommerce-app-159.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-159.firebasestorage.app',
  );

}